/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aulabd;

/**
 *
 * @author laboratorio
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadPessoa = new javax.swing.JMenuItem();
        menuEditarExcluirPessoa = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuRelPessoa = new javax.swing.JMenuItem();
        menuRelFiltro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Arquivo");

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastro");

        menuCadPessoa.setText("Cadastro de Pessoas");
        menuCadPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadPessoaActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadPessoa);

        menuEditarExcluirPessoa.setText("Editar e Excluir Pessoas");
        menuEditarExcluirPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarExcluirPessoaActionPerformed(evt);
            }
        });
        jMenu2.add(menuEditarExcluirPessoa);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatório");

        menuRelPessoa.setText("Relatório Pessoas");
        menuRelPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelPessoaActionPerformed(evt);
            }
        });
        jMenu3.add(menuRelPessoa);

        menuRelFiltro.setText("Relatório com Filtro");
        menuRelFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelFiltroActionPerformed(evt);
            }
        });
        jMenu3.add(menuRelFiltro);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadPessoaActionPerformed
        Adicionar cadPessoa = new Adicionar();
        cadPessoa.setVisible(true);
    }//GEN-LAST:event_menuCadPessoaActionPerformed

    private void menuEditarExcluirPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarExcluirPessoaActionPerformed
        EditarExcluir edtexcPessoa = new EditarExcluir();
        edtexcPessoa.setVisible(true);
    }//GEN-LAST:event_menuEditarExcluirPessoaActionPerformed

    private void menuRelPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelPessoaActionPerformed
        RelatorioPessoas relPessoa = new RelatorioPessoas();
        relPessoa.setVisible(true);
    }//GEN-LAST:event_menuRelPessoaActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        //this.dispose(); - fecha a tela
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuRelFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelFiltroActionPerformed
        RelatorioFiltro relPessoaFiltro = new RelatorioFiltro();
        relPessoaFiltro.setVisible(true);
    }//GEN-LAST:event_menuRelFiltroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCadPessoa;
    private javax.swing.JMenuItem menuEditarExcluirPessoa;
    private javax.swing.JMenuItem menuRelFiltro;
    private javax.swing.JMenuItem menuRelPessoa;
    private javax.swing.JMenuItem menuSair;
    // End of variables declaration//GEN-END:variables
}
