USE EMPRESA;

-- INNER JOIN
SELECT F.Pnome, F.Unome, D.Dnome
FROM FUNCIONARIO AS F
INNER JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
WHERE D.Dnome = 'Pesquisa';

SELECT F.Pnome, F.Unome
FROM FUNCIONARIO AS F
INNER JOIN TRABALHA_EM AS TE 
ON TE.Fcpf = F.Cpf
INNER JOIN PROJETO AS P
ON TE.Pnr = P.Projnumero
WHERE P.Projnome = 'ProdutoX';

SELECT 
	P.Projnumero, 
	D.Dnumero, 
	F.Unome,
	F.Endereco, 
	F.Datanasc
FROM PROJETO AS P
INNER JOIN DEPARTAMENTO AS D
	ON P.Dnum = D.Dnumero
INNER JOIN FUNCIONARIO AS F
	ON D.Cpf_gerente = F.Cpf
WHERE P.Projlocal = 'Mauá';

-- LEFT JOIN
SELECT F.Unome AS Funcionario, G.Unome as Gerente
FROM FUNCIONARIO AS F
LEFT JOIN FUNCIONARIO AS G
ON G.Cpf = F.Cpf_supervisor;

SELECT D.Dnome, D.Dnumero
FROM DEPARTAMENTO AS D
LEFT JOIN FUNCIONARIO AS F
ON D.Dnumero = F.Dnr 
WHERE F.Cpf IS NULL;

SELECT F.Pnome, F.Unome
FROM FUNCIONARIO AS F
WHERE F.Dnr IS NULL;

-- RIGHT JOIN
SELECT D.Dnome, D.Dnumero
FROM FUNCIONARIO AS F
RIGHT JOIN DEPARTAMENTO AS D
ON D.Dnumero = F.Dnr 
WHERE F.Cpf IS NULL;

-- CROSS JOIN
SELECT *
FROM FUNCIONARIO AS F
FULL JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero;

-- SELF JOIN
SELECT F.Unome AS Funcionario, G.Unome as Gerente
FROM FUNCIONARIO AS F
JOIN FUNCIONARIO AS G
ON G.Cpf = F.Cpf_supervisor;

-- UNION
SELECT F.Pnome , F.Sexo, F.Datanasc
FROM FUNCIONARIO AS F
UNION
SELECT D.Nome_dependente, D.Sexo, D.Datanasc
FROM DEPENDENTE AS D

SELECT LD.Dlocal
FROM LOCALIZACAO_DEP AS LD
UNION
SELECT D.Projlocal
FROM PROJETO AS D;

SELECT LD.Dlocal
FROM LOCALIZACAO_DEP AS LD
UNION ALL
SELECT D.Projlocal
FROM PROJETO AS D;

-- EXCEPT
SELECT F.Cpf
FROM FUNCIONARIO AS F
EXCEPT
SELECT D.Cpf_gerente
FROM DEPARTAMENTO AS D;


SELECT F.Pnome, F.Unome
FROM FUNCIONARIO AS F
WHERE F.Cpf IN (SELECT F.Cpf
				FROM FUNCIONARIO AS F
				EXCEPT 
				SELECT S.Cpf_supervisor
				FROM FUNCIONARIO AS S);

-- INTERSECT
SELECT F.Cpf
FROM FUNCIONARIO AS F
INTERSECT
SELECT D.Cpf_gerente
FROM DEPARTAMENTO AS D;

-- GROUP BY
SELECT COUNT(F.Cpf) AS 'NumFuncionarios', D.Dnome AS 'Departamento'
FROM FUNCIONARIO AS F
JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
GROUP BY D.Dnome;

SELECT SUM(F.Salario) AS 'TotalSalarios', D.Dnome AS 'Departamento'
FROM FUNCIONARIO AS F
JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
GROUP BY D.Dnome;

SELECT AVG(TE.Horas) AS 'MediaHoras', P.Projnome AS 'Projeto'
FROM TRABALHA_EM AS TE 
JOIN PROJETO AS P
ON TE.Pnr = P.Projnumero
GROUP BY P.Projnome;

SELECT COUNT(*), F.Sexo
FROM FUNCIONARIO AS F
GROUP BY F.Sexo;

SELECT MAX(F.Salario), D.Dnome
FROM FUNCIONARIO AS F
JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
GROUP BY D.Dnome;

-- HAVING 
SELECT COUNT(F.Cpf) AS 'NumFuncionarios', D.Dnome AS 'Departamento'
FROM FUNCIONARIO AS F
JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
GROUP BY D.Dnome
HAVING COUNT(F.Cpf) > 3;

SELECT SUM(TE.Horas) AS 'Horas', P.Projnome AS 'Projeto'
FROM TRABALHA_EM AS TE
JOIN PROJETO AS P
ON TE.Pnr = P.Projnumero
GROUP BY P.Projnome
HAVING SUM(TE.Horas) >= 50;

-- EXISTS
SELECT F.Pnome, F.Unome, F.Cpf
FROM FUNCIONARIO AS F
WHERE EXISTS (
				SELECT 1
				FROM DEPARTAMENTO AS D
				WHERE D.Cpf_gerente = F.Cpf
				);
