/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package escola;

/**
 *
 * @author luiza
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadAluno = new javax.swing.JMenuItem();
        menuCadProfessor = new javax.swing.JMenuItem();
        menoEditarAluno = new javax.swing.JMenuItem();
        menuEditarProf = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuRelatorioAlunos = new javax.swing.JMenuItem();
        menuRelatorioProf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Arquivo");

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        MenuBar.add(jMenu1);

        jMenu2.setText("Cadastro");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menuCadAluno.setText("Cadastro Aluno");
        menuCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadAlunoActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadAluno);

        menuCadProfessor.setText("Cadastro Professor");
        menuCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProfessorActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadProfessor);

        menoEditarAluno.setText("Editar e Excluir Aluno");
        menoEditarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoEditarAlunoActionPerformed(evt);
            }
        });
        jMenu2.add(menoEditarAluno);

        menuEditarProf.setText("Editar e Excluir Professor");
        menuEditarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarProfActionPerformed(evt);
            }
        });
        jMenu2.add(menuEditarProf);

        MenuBar.add(jMenu2);

        jMenu3.setText("Relatório");

        menuRelatorioAlunos.setText("Relatório Alunos");
        menuRelatorioAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioAlunosActionPerformed(evt);
            }
        });
        jMenu3.add(menuRelatorioAlunos);

        menuRelatorioProf.setText("Relatório Professores");
        menuRelatorioProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioProfActionPerformed(evt);
            }
        });
        jMenu3.add(menuRelatorioProf);

        MenuBar.add(jMenu3);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadAlunoActionPerformed
        AdicionarAluno cadAluno = new AdicionarAluno();
        cadAluno.setVisible(true);
    }//GEN-LAST:event_menuCadAlunoActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void menuCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProfessorActionPerformed
        AdicionarProfessor cadProf = new AdicionarProfessor();
        cadProf.setVisible(true);
    }//GEN-LAST:event_menuCadProfessorActionPerformed

    private void menoEditarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoEditarAlunoActionPerformed
        EditarExcluirAluno edtAluno = new EditarExcluirAluno();
        edtAluno.setVisible(true);
    }//GEN-LAST:event_menoEditarAlunoActionPerformed

    private void menuEditarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarProfActionPerformed
        EditarExcluirProfessor edtProf = new EditarExcluirProfessor();
        edtProf.setVisible(true);
    }//GEN-LAST:event_menuEditarProfActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuRelatorioAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioAlunosActionPerformed
        RelatorioAlunos relAlunos = new RelatorioAlunos();
        relAlunos.setVisible(true);
    }//GEN-LAST:event_menuRelatorioAlunosActionPerformed

    private void menuRelatorioProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioProfActionPerformed
        RelatorioProfessores relProf = new RelatorioProfessores();
        relProf.setVisible(true);
    }//GEN-LAST:event_menuRelatorioProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem menoEditarAluno;
    private javax.swing.JMenuItem menuCadAluno;
    private javax.swing.JMenuItem menuCadProfessor;
    private javax.swing.JMenuItem menuEditarProf;
    private javax.swing.JMenuItem menuRelatorioAlunos;
    private javax.swing.JMenuItem menuRelatorioProf;
    private javax.swing.JMenuItem menuSair;
    // End of variables declaration//GEN-END:variables
}
