SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

-- Transação 1
BEGIN TRAN;
SELECT * FROM FUNCIONARIO;
PRINT 'SELECT concluido em: ' + CONVERT(VARCHAR(23), SYSDATETIME(),121)

-- Pausa de 20 segundos
WAITFOR DELAY '00:00:20'
COMMIT TRAN;
PRINT 'COMMIT em: ' + CONVERT(VARCHAR(23), SYSDATETIME(),121)

-- Transação 2
BEGIN TRAN;
INSERT INTO FUNCIONARIO (Pnome, Minicial, Unome, Cpf)
VALUES ('Luiza', 'L', 'Karlec', '5263742')
PRINT 'INSERT concluido em: ' + CONVERT(VARCHAR(23), SYSDATETIME(),121)
COMMIT TRAN;
PRINT 'COMMIT em: ' + CONVERT(VARCHAR(23), SYSDATETIME(),121)