USE [master]
GO
CREATE LOGIN [Vanessa] WITH PASSWORD=N'123456', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
use [master];
GO
USE [EMPRESA]
GO
CREATE USER [Vanessa] FOR LOGIN [Vanessa]
GO
USE [EMPRESA]
GO
ALTER ROLE [db_datareader] ADD MEMBER [Vanessa]
GO
