USE EMPRESA;

SELECT * FROM FUNCIONARIO;

INSERT INTO FUNCIONARIO(Pnome, Unome, Cpf)
VALUES ('Eric', 'Martins', '123');

UPDATE FUNCIONARIO
SET Pnome = 'Herique'
WHERE Cpf = '123';

DELETE FROM FUNCIONARIO
WHERE Cpf = '123';